# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  authservice:
    image: authservice
    environment:
      - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
    build:
      context: .
      dockerfile: Services/AuthService/Dockerfile
    ports:
      - 8080:8080
    networks:
      - backend
  vocabularyservice:
    image: vocabularyservice
    environment:
      - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
    build: 
      context: .
      dockerfile: Services/VocabularyService/Dockerfile
      
    ports:
      - 8081:8081
    networks:
      - backend

  apigateway:
    image: nginx:alpine
    container_name: apigateway
    ports:
      - "80:80"
    volumes:
      - ./GateWay/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - authservice
      - vocabularyservice
    networks:
      - backend

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
volumes:
  pgdata:

networks:
  backend:
    driver: bridge